annuaire/Models/Service.cs
using Microsoft.EntityFrameworkCore;

namespace annuaire.Models;

using System.ComponentModel.DataAnnotations;

[PrimaryKey(nameof(Id))]
public class Service : BaseEntity
{
    public int Id { get; set; }

    [Key]
    [StringLength(50, ErrorMessage = "Le nom du service ne soit pas dépasser 50 caractère et minimum 2 caractères",
        MinimumLength = 2)]
    public string Name { get; set; }

    public ICollection<Employee?>? Employees { get; set; }
}

annuaire/Controllers/ServiceController.cs
using annuaire.Models;
using annuaire.Services.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace annuaire.Controllers;

public class ServiceController : Controller
{
    private readonly IServiceService _serviceService;

    public ServiceController(IServiceService serviceService)
    {
        _serviceService = serviceService;
    }

    //list all services
    public async Task<IActionResult> Index(int page = 1)
    {
        ActionResult<List<Service>> services = await _serviceService.ListAllServices(page);
        ActionResult<int> pages = await _serviceService.GetNumberPage();
        ViewBag.NumberPage = pages.Value;
        return View(services.Value);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        ActionResult<Service> site = await _serviceService.GetServiceById(id);
        return View(site.Value);
    }

    [HttpPost]
    public async Task<IActionResult> Update(int id, Service service)
    {
        if (id != service.Id)
        {
            return new BadRequestResult();
        }

        ActionResult<Service> serviceToUpdate = await _serviceService.GetServiceById(id);
        if (serviceToUpdate.Value == null)
        {
            return new NotFoundResult();
        }

        if (!ModelState.IsValid)
        {
            return Redirect($"/Service/Get/{service.Id}");
        }

        try
        {
            bool exist = await _serviceService.IsServiceAlreadyExiste(service);
            if (exist)
            {
                ModelState.AddModelError("Name", "Ce nom est déjà utilisé.");
                return View(service);
            }

            await _serviceService.UpdateService(service);
        }
        catch (DbUpdateConcurrencyException)
        {
            return new NotFoundResult();
        }

        return Redirect($"/Service/Get/{service.Id}");
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Service service)
    {
        if (!ModelState.IsValid)
        {
            return View(service);
        }

        try
        {
            bool exist = await _serviceService.IsServiceAlreadyExiste(service);
            if (exist)
            {
                ModelState.AddModelError("Name", "Ce nom est déjà utilisé.");
                return View(service);
            }

            await _serviceService.CreateService(service);
        }
        catch (DbUpdateConcurrencyException)
        {
            return new NotFoundResult();
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [Route("Service/Delete/{id:int}")]
    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        ActionResult<Service> service = await _serviceService.GetServiceById(id);

        if (service.Value == null)
        {
            return new NotFoundResult();
        }

        if (service.Value.Employees!.Count == 0)
        {
            await _serviceService.DeleteService(service.Value);
        }
        else
        {
            return Redirect("/Service/Index");
        }

        return Redirect("/Service/Index");
    }
}

annuaire/Views/Service/Create.cshtml
@model annuaire.Models.Service
@{
    ViewBag.Title = "Créer un service";
    Layout = "_Layout";
}

@section scripts{
    <partial name="_ValidationScriptsPartial"/>
}

<h2>Créer un service</h2>
<form method="POST" asp-action="Create" asp-controller="Service">
    <label asp-for="Name">Nom du service</label>
    <input class="form-control" asp-for="Name"/>
    <span asp-validation-for="Name"></span>
    <br/>
    <input class="btn btn-success" type="submit" value="Créer"/>
</form>

annuaire/Views/Service/Index.cshtml
@model List<annuaire.Models.Service>

@{
    ViewBag.Title = "Services";
    Layout = "_Layout";
}

<h2>Liste des services</h2>
@if (Model.Count > 0)
{
    @if (User.Identity!.IsAuthenticated)
    {
        <a href="@Url.Action("Create", "Service")" class="btn btn-success">Créer un service</a>
    }
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Action</th>
            @if (User.Identity!.IsAuthenticated && User.IsInRole("admin"))
            {
                <th>Admins</th>
            }
        </tr>
        </thead>
        <tbody>
        @foreach (var service in Model)
        {
            <tr>
                <td>@service.Name</td>
                <td>
                    <a href="/Employee/Search?Service=@service.Id" class="btn btn-primary">Voir les employés</a>
                </td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <a href="@Url.Action("Update", "Service", new { id = service.Id })" class="btn btn-primary">Edit</a>
                        @using (Html.BeginForm("Delete", "Service", new { id = service.Id }, FormMethod.Post))
                        {
                            <button type="submit" class="btn btn-danger">Delete</button>
                        }
                    </td>
                }
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <p>No employees found.</p>
}

<nav aria-label="...">
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.NumberPage; i++)
        {
            int page;
            @if (Context.Request.Query["page"].ToString() == "")
            {
                page = 1;
            }
            else
            {
                page = int.Parse(Context.Request.Query["page"].ToString());
            }
            <li class="page-item @(page == i ? "active" : "")">
                <a class="page-link" href="/Service/Index?page=@i">@i</a>
            </li>
        }
    </ul>
</nav>

annuaire/Views/Service/Update.cshtml
@model annuaire.Models.Service
@{
    ViewBag.Title = "Mettre à jour";
    Layout = "_Layout";
}

<h2>@Model.Name</h2>

@if (User.Identity!.IsAuthenticated)
{
    <form method="POST" asp-action="Update" asp-controller="Service">
        <input type="hidden" name="Id" value="@Model.Id"/>
        <label>Nom du service</label>
        <input asp-for="Name" class="form-control" type="text" name="Name" value="@Model.Name"/>
        <span asp-validation-for="Name"></span>
        <input class="btn btn-success" type="submit" value="Mettre à jour"/>
    </form>
}
else
{
    <div class="d-flex">
        <label>Nom du service</label>
        <p class="form-control" type="text" name="Name" value="@Model.Name"/>
    </div>
}