annuaire/Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace annuaire.Models;

[PrimaryKey(nameof(Id))]
public class Employee : BaseEntity
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Le prénom est obligatoire")]
    [StringLength(50, ErrorMessage = "Le prénom ne doit pas dépasser 50 caractères et minimum 2 caractères",
        MinimumLength = 2)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50, ErrorMessage = "Le nom ne doit pas dépasser 50 caractères et minimum 2 caractères",
        MinimumLength = 2)]
    public string LastName { get; set; }

    [Required]
    [EmailAddress(ErrorMessage = "L'adresse email n'est pas valide")]
    [StringLength(60, ErrorMessage = "L'email ne doit pas dépasser 60 caractères")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Le téléphone portable est obligatoire")]
    [Phone(ErrorMessage = "Le numéro de téléphone portable n'est pas valide")]
    public string MobilePhone { get; set; }

    [Required(ErrorMessage = "Le téléphone fixe est obligatoire")]
    [Phone(ErrorMessage = "Le numéro de téléphone fixe n'est pas valide")]
    public string FixedPhone { get; set; }

    [NotMapped] public string? Password { get; set; }

    [Column(TypeName = "boolean")] public bool IsAdmin { get; set; }

    public Service? Service { get; set; }

    public Site? Site { get; set; }
}

annuaire/Controllers/EmployeeController.cs
using annuaire.Models;
using annuaire.Services.Employee;
using annuaire.Services.Service;
using annuaire.Services.Site;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace annuaire.Controllers;

public class EmployeeController : Controller
{
    //import services
    private readonly IEmployeeService _employeeService;
    private readonly IServiceService _serviceService;
    private readonly ISiteService _siteService;

    public EmployeeController(IEmployeeService employeeService, IServiceService serviceService,
        ISiteService siteService)
    {
        _employeeService = employeeService;
        _siteService = siteService;
        _serviceService = serviceService;
    }

    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        ActionResult<Employee> employee = await _employeeService.GetEmployeeById(id);
        var services = await _serviceService.ListAllServicesWithoutPagination();
        if (services.Value != null)
        {
            ViewBag.Services = services.Value;
        }

        var sites = await _siteService.ListAllSiteWithoutPagination();
        if (sites.Value != null)
        {
            ViewBag.Sites = sites.Value;
        }

        return View(employee.Value);
    }

    [HttpPost]
    public async Task<IActionResult> Update([FromForm] int id, Employee employee)
    {
        if (id != employee.Id)
        {
            return View(employee);
        }

        var services = await _serviceService.ListAllServicesWithoutPagination();
        //to send the list of services to the view
        if (services.Value != null)
        {
            ViewBag.Services = services.Value;
        }

        var sites = await _siteService.ListAllSiteWithoutPagination();
        if (sites.Value != null)
        {
            ViewBag.Sites = sites.Value;
        }

        ActionResult<Employee> employeeToUpdate = await _employeeService.GetEmployeeById(id);
        if (employeeToUpdate.Value == null)
        {
            return new NotFoundResult();
        }

        var serviceId = Request.Form["Service"];
        var siteId = Request.Form["Site"];
        if (serviceId != "" && siteId != "")
        {
            var service = await _serviceService.GetServiceById(int.Parse(serviceId));
            if (service.Value == null)
            {
                ModelState.AddModelError("Service", "Le service est nécessaire");
                return View(employee);
            }

            var site = await _siteService.GetSiteById(int.Parse(siteId));
            if (site.Value == null)
            {
                ModelState.AddModelError("Site", "Le site est nécessaire");
                return View(employee);
            }

            employee.Service = service.Value;
            employee.Site = site.Value;
        }
        else
        {
            ModelState.AddModelError("Service", "Le service est nécessaire");
            ModelState.AddModelError("Site", "Le site est nécessaire");
            return View(employee);
        }

        if (!ModelState.IsValid)
        {
            return View(employee);
        }

        try
        {
            bool exist = await _employeeService.GetEmployeeByEmailAndId(employee.Email, employee.Id);
            if (exist)
            {
                ModelState.AddModelError("Email", "Cette email existe déjà");
                return View(employee);
            }

            await _employeeService.UpdateEmployee(employee);
        }
        catch (DbUpdateConcurrencyException)
        {
            return new NotFoundResult();
        }


        return View(employee);
    }

    [HttpGet]
    public async Task<IActionResult> Search()
    {
        var queryDict = new Dictionary<string, string>();
        foreach (var key in Request.Query)
        {
            queryDict.Add(key.Key, key.Value!);
        }

        int page = queryDict.ContainsKey("page") ? int.Parse(queryDict["page"]) : 1;
        var result = await _employeeService.ListWithFilters(queryDict, page);

        var services = await _serviceService.ListAllServicesWithoutPagination();
        if (services.Value != null)
        {
            ViewBag.Services = services.Value;
        }

        var sites = await _siteService.ListAllSiteWithoutPagination();
        if (sites.Value != null)
        {
            ViewBag.Sites = sites.Value;
        }

        ViewBag.NumberPage = result.Item2;
        ViewBag.Page = page;
        return View(result.Item1.Value);
    }

    [HttpPost]
    [Route("Employee/Delete/{id:int}")]
    [Authorize]
    public IActionResult Delete(int id)
    {
        var token = HttpContext.User.Identities.First().Claims.First().Value;
        ActionResult<Employee> currentEmployee = _employeeService.GetEmployeeById(int.Parse(token)).Result;
        if (currentEmployee.Value == null)
        {
            return new NotFoundResult();
        }

        if (currentEmployee.Value.Id == id)
        {
            return new BadRequestResult();
        }

        ActionResult<Employee> employee = _employeeService.GetEmployeeById(id).Result;

        if (employee.Value == null)
        {
            return new NotFoundResult();
        }

        _employeeService.DeleteEmployee(employee.Value);
        return Redirect("/Employee/Search");
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var services = await _serviceService.ListAllServicesWithoutPagination();
        if (services.Value != null)
        {
            ViewBag.Services = services.Value;
        }

        var sites = await _siteService.ListAllSiteWithoutPagination();
        if (sites.Value != null)
        {
            ViewBag.Sites = sites.Value;
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromForm] Employee employee)
    {
        var serviceId = Request.Form["Service"];
        var siteId = Request.Form["Site"];
        //to send the list of services to the view
        if (serviceId != "" && siteId != "")
        {
            var service = await _serviceService.GetServiceById(int.Parse(serviceId));
            if (service.Value == null)
            {
                ModelState.AddModelError("Service", "Ce service n'existe pas");
                return View(employee);
            }

            var site = await _siteService.GetSiteById(int.Parse(siteId));
            if (site.Value == null)
            {
                ModelState.AddModelError("Site", "Ce site n'existe pas");
                return View(employee);
            }

            employee.Service = service.Value;
            employee.Site = site.Value;
        }
        else
        {
            var services = await _serviceService.ListAllServicesWithoutPagination();
            if (services.Value != null)
            {
                ViewBag.Services = services.Value;
            }

            var sites = await _siteService.ListAllSiteWithoutPagination();
            if (sites.Value != null)
            {
                ViewBag.Sites = sites.Value;
            }

            ModelState.AddModelError("Service", "Ce service n'existe pas");
            ModelState.AddModelError("Site", "Ce site n'existe pas");
            return View(employee);
        }

        if (!ModelState.IsValid)
        {
            var services = await _serviceService.ListAllServicesWithoutPagination();
            if (services.Value != null)
            {
                ViewBag.Services = services.Value;
            }

            var sites = await _siteService.ListAllSiteWithoutPagination();
            if (sites.Value != null)
            {
                ViewBag.Sites = sites.Value;
            }

            return View(employee);
        }

        try
        {
            bool exist = await _employeeService.GetEmployeeByEmail(employee.Email);
            if (exist)
            {
                var services = await _serviceService.ListAllServicesWithoutPagination();
                if (services.Value != null)
                {
                    ViewBag.Services = services.Value;
                }

                var sites = await _siteService.ListAllSiteWithoutPagination();
                if (sites.Value != null)
                {
                    ViewBag.Sites = sites.Value;
                }

                ModelState.AddModelError("Email", "Cette email existe déjà");
                return View(employee);
            }

            await _employeeService.CreateEmployee(employee);
        }
        catch (DbUpdateConcurrencyException)
        {
            return new NotFoundResult();
        }

        return Redirect("/Employee/Search");
    }
}

annuaire/Views/Employee/Create.cshtml
@model annuaire.Models.Employee
@{
    ViewBag.Title = "Créer un service";
    Layout = "_Layout";
}

@section scripts{
    <partial name="_ValidationScriptsPartial"/>
}

<h2>Créer un employé</h2>
<form method="POST" asp-action="Create" asp-controller="Employee">
    <label>Prénom</label>
    <input asp-for="FirstName"/>
    <span asp-validation-for="FirstName"></span>
    <br/>
    <label>Nom</label>
    <input asp-for="LastName"/>
    <span asp-validation-for="LastName"></span>
    <br/>
    <label>Email</label>
    <input asp-for="Email"/>
    <span asp-validation-for="Email"></span>
    <br/>
    <label>Téléphone portable</label>
    <input asp-for="MobilePhone"/>
    <span asp-validation-for="MobilePhone"></span>
    <br/>
    <label>Téléphone fixe</label>
    <input asp-for="FixedPhone"/>
    <span asp-validation-for="FixedPhone"></span>
    <br/>
    <label>Administrateur</label>
    <input asp-for="IsAdmin"/>
    <br/>
    <div class="input-group mb-3">
        <select class="form-select" aria-label="Default select example" name="Service">
            <option value="">Choisir un service</option>
            @foreach (Service service in ViewBag.Services)
            {
                <option value="@service.Id" selected="@(Context.Request.Query["Service"] == service.Id.ToString())">@service.Name</option>
            }
        </select>
        <span asp-validation-for="Service"></span>
        <select class="form-select" aria-label="Default select example" name="Site">
            <option value="">Choisir un site</option>
            @foreach (Site site in ViewBag.Sites)
            {
                <option value="@site.Id" selected="@(Context.Request.Query["Site"] == site.Id.ToString())">@site.City</option>
            }
        </select>
        <span asp-validation-for="Site"></span>
    </div>
    <input class="btn btn-success" type="submit" value="Créer l'employé"/>
</form>

annuaire/Views/Employee/Search.cshtml
@model List<annuaire.Models.Employee>?

@{
    ViewBag.Title = "Employés";
    Layout = "_Layout";
}
@if (User.Identity!.IsAuthenticated)
{
    <a href="@Url.Action("Create", "Employee")" class="btn btn-success">Créer un employé</a>
}

@using (Html.BeginForm("Search", "Employee", FormMethod.Get))
{
    <div class="d-flex">
        <input class="input-group-text" type="text" name="FirstName" placeholder="Prénom" value="@(Context.Request.Query["FirstName"])"/>
        <input class="input-group-text" type="text" name="LastName" placeholder="Nom" value="@(Context.Request.Query["LastName"])"/>
        <input class="input-group-text" type="text" name="Email" placeholder="Email" value="@(Context.Request.Query["Email"])"/>
    </div>
    <br/>
    <div class="d-flex">
        <input class="input-group-text" type="text" name="MobilePhone" placeholder="Téléphone Portable" value="@(Context.Request.Query["MobilePhone"])"/>
        <input class="input-group-text" type="text" name="FixedPhone" placeholder="Téléphone Fixe" value="@(Context.Request.Query["FixedPhone"])"/>
    </div>
    <br/>
    <div class="input-group mb-3">
        <select class="form-select" aria-label="Default select example" name="Service">
            <option value="">Choisir un service</option>
            @foreach (Service service in ViewBag.Services)
            {
                <option value="@service.Id" selected="@(Context.Request.Query["Service"] == service.Id.ToString())">@service.Name</option>
            }
        </select>
        <select class="form-select" aria-label="Default select example" name="Site">
            <option value="">Choisir un site</option>
            @foreach (Site site in ViewBag.Sites)
            {
                <option value="@site.Id" selected="@(Context.Request.Query["Site"] == site.Id.ToString())">@site.City : @site.Description</option>
            }
        </select>
    </div>
    <div class="d-flex">
        <button class="btn-success btn" type="submit">Submit</button>
    </div>
}

@if (Model?.Count > 0)
{
    <h2>Résultat</h2>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Email</th>
            <th scope="col">Téléphone portable</th>
            <th scope="col">Téléphone fixe</th>
            <th scope="col">Service</th>
            <th scope="col">Site</th>
            @if (User.Identity!.IsAuthenticated)
            {
                <th>Actions</th>
            }
        </tr>
        </thead>
        <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.FirstName</td>
                <td>@employee.LastName</td>
                <td>@employee.Email</td>
                <td>@employee.MobilePhone</td>
                <td>@employee.FixedPhone</td>
                <td>@employee.Service.Name</td>
                <td>@employee.Site.City : @employee.Site.Description</td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <a href="@Url.Action("Update", "Employee", new { id = employee.Id })" class="btn btn-primary">Edit</a>

                        @if (User.Claims.First().Value == employee.Id.ToString())
                        {
                            @using (Html.BeginForm("Delete", "Employee", new { id = employee.Id }, FormMethod.Post))
                            {
                                <button type="submit" class="btn btn-danger disabled">Delete</button>
                            }
                        }
                        else
                        {
                            @using (Html.BeginForm("Delete", "Employee", new { id = employee.Id }, FormMethod.Post))
                            {
                                <button type="submit" class="btn btn-danger">Delete</button>
                            }
                        }

                    </td>
                }
            </tr>
        }
        </tbody>
    </table>
    <nav aria-label="...">
        <ul class="pagination">
            @for (var i = (Math.Max(1, ViewBag.Page - 2)); i <= (Math.Min(ViewBag.Page + 2, ViewBag.NumberPage)); i++)
            {
                int page;
                @if (Context.Request.Query["page"].ToString() == "")
                {
                    page = 1;
                }
                else
                {
                    page = int.Parse(Context.Request.Query["page"].ToString());
                }
                Dictionary<string, string> Dico = new Dictionary<string, string>();
                var href = "/Employee/Search?page=" + i + "&";
                foreach (var item in Context.Request.Query)
                {
                    if (item.Key != "page")
                    {
                        Dico.Add(item.Key, item.Value);

                        href += item.Key + "=" + Uri.EscapeDataString(item.Value) + "&";
                    }
                }
                <li class="page-item @(page == i ? "active" : "")">
                    <a class="page-link" href=@(href)>@i</a>
                </li>
            }
        </ul>
    </nav>
}
else
{
    <p>Aucun résultat</p>
}

annuaire/Views/Employee/Update.cshtml
@using System.CodeDom
@model annuaire.Models.Employee
@{
    ViewBag.Title = "Mettre à jour";
    Layout = "_Layout";
}

<h2>@Model.FirstName @Model.LastName</h2>

@if (User.Identity!.IsAuthenticated)
{
    <form method="POST" asp-action="Update" asp-controller="Employee">
        <input type="hidden" name="Id" value="@Model.Id"/>
        <label>Prénom</label>
        <input class="form-control" type="text" asp-for="FirstName" name="FirstName" value="@Model.FirstName"/>
        <span asp-validation-for="FirstName"></span>
        <br/>
        <label>Nom</label>
        <input class="form-control" type="text" name="LastName" value="@Model.LastName"/>
        <span asp-validation-for="LastName"></span>
        <br/>
        <label>Email</label>
        <input asp-for="Email" class="form-control" type="email" value="@Model.Email"/>
        <span asp-validation-for="Email"></span>
        <br/>
        <label>Téléphone portable</label>
        <input asp-for="MobilePhone" value="@Model.MobilePhone"/>
        <span asp-validation-for="MobilePhone"></span>
        <br/>
        <label>Téléphone fixe</label>
        <input asp-for="FixedPhone" value="@Model.FixedPhone"/>
        <span asp-validation-for="FixedPhone"></span>
        <br/>
        <label>Administrateur</label>
        <input class="form-check-input" type="checkbox" name="Administrateur" value="@Model.IsAdmin"/>
        <span asp-validation-for="IsAdmin"></span>
        <br/>
        <label>Mot de Passe</label>
        <input class="form-control" type="password" name="Password"/>
        <br/>
        <div class="input-group mb-3">
            <select class="form-select" aria-label="Default select example" name="Service">
                <option value="">Choisir un service</option>
                @foreach (Service service in ViewBag.Services)
                {
                    <option value="@service.Id" selected="@(Model.Service.Id == service.Id)">@service.Name</option>
                }
            </select>
            <span asp-validation-for="Service"></span>
            <select class="form-select" aria-label="Default select example" name="Site">
                <option value="">Choisir un site</option>
                @foreach (Site site in ViewBag.Sites)
                {
                    <option value="@site.Id" selected="@(Model.Site.Id == site.Id)">@site.City</option>
                }
            </select>
            <span asp-validation-for="Site"></span>
        </div>
        <br/>
        <input type="submit" value="Mettre à jour"/>
    </form>
}