annuaire/Models/Site.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace annuaire.Models;

[PrimaryKey(nameof(Id))]
public class Site : BaseEntity
{
    public int Id { get; set; }

    [Column(TypeName = "varchar(50)")]
    [StringLength(50, ErrorMessage = "La description du site ne soit pas dépasser 50 caractère et minimum 2 caractères",
        MinimumLength = 2)]
    public string Description { get; set; }

    [Column(TypeName = "varchar(50)")]
    [StringLength(50, ErrorMessage = "La ville du site ne soit pas dépasser 50 caractère et minimum 2 caractères",
        MinimumLength = 2)]
    public string City { get; set; }

    public ICollection<Employee?>? Employee { get; set; }
}

annuaire/Controllers/SiteController.cs
using annuaire.Models;
using annuaire.Services.Site;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace annuaire.Controllers;

public class SiteController : Controller
{
    private readonly ISiteService _siteService;

    public SiteController(ISiteService siteService)
    {
        _siteService = siteService;
    }

    public async Task<IActionResult> Index(int page = 1)
    {
        ActionResult<List<Site>> site = await _siteService.ListAllSite(page);
        ActionResult<int> pages = await _siteService.GetNumberPage();
        ViewBag.NumberPage = pages.Value;
        return View(site.Value);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        ActionResult<Site> site = await _siteService.GetSiteById(id);
        return View(site.Value);
    }

    [HttpPost]
    public async Task<IActionResult> Update(int id, Site site)
    {
        if (id != site.Id)
        {
            return new BadRequestResult();
        }

        ActionResult<Site> siteToUpdate = await _siteService.GetSiteById(id);
        if (siteToUpdate.Value == null)
        {
            return new NotFoundResult();
        }

        if (!ModelState.IsValid)
        {
            return View(site);
        }

        try
        {
            bool exist = await _siteService.IsSiteAlreadyExist(site);
            if (exist)
            {
                ModelState.AddModelError("City", "Ce site existe déjà");
                    return View(site);
            }

            await _siteService.UpdateSite(site);
        }
        catch (DbUpdateConcurrencyException)
        {
            return new NotFoundResult();
        }

        return View(site);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Site site)
    {
        if (!ModelState.IsValid)
        {
            return View(site);
        }

        try
        {
            bool exist = await _siteService.IsSiteAlreadyExist(site);
            if (exist)
            {
                ModelState.AddModelError("City", "Ce site existe déjà");
                return View(site);
            }

            await _siteService.CreateSite(site);
        }
        catch (DbUpdateConcurrencyException)
        {
            return new NotFoundResult();
        }

        return Redirect($"/Site/Get/{site.Id}");
    }

    [HttpPost]
    [Route("Site/Delete/{id:int}")]
    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        ActionResult<Site> site = await _siteService.GetSiteById(id);
        if (site.Value == null)
        {
            return new NotFoundResult();
        }

        //to not delete if there remaning user
        if (site.Value.Employee!.Count == 0)
        {
            await _siteService.DeleteSite(site.Value);
        }
        else
        {
            return Redirect("/Site/Index");
        }

        return Redirect("/Site/Index");
    }
}

annuaire/Views/Site/Create.cshtml
@model annuaire.Models.Site

@{
    ViewBag.Title = "Créer un site";
    Layout = "_Layout";
}

<h2>Créer un site</h2>
<form method="POST" asp-action="Create" asp-controller="Site">
    <label>Ville</label>
    <input asp-for="City"/>
    <span asp-validation-for="City"></span>
    <br/>
    <label>Description</label>
    <input asp-for="Description"/>
    <span asp-validation-for="Description"></span>
    <br/>
    <input class="btn btn-success" type="submit" value="Créer à jour"/>
</form>

annuaire/Views/Site/Index.cshtml
@model List<annuaire.Models.Site>

@{
    ViewBag.Title = "Sites";
    Layout = "_Layout";
}

<h2>Liste des sites</h2>
@if (Model.Count > 0)
{
    @if (User.Identity!.IsAuthenticated)
    {
        <a href="@Url.Action("Create", "Site")" class="btn btn-success">Créer un site</a>
    }
    <table>
        <thead>
        <tr>
            <th>Ville</th>
            <th>Description</th>
            <th>Action</th>
            @if (User.Identity!.IsAuthenticated && User.IsInRole("admin"))
            {
                <th>Admin</th>
            }
        </tr>
        </thead>
        <tbody>
        @foreach (var site in Model)
        {
            <tr>
                <td>@site.City</td>
                <td>@site.Description</td>
                <td>
                    <a href="/Employee/Search?Site=@site.Id" class="btn btn-primary">Voir les employés</a>
                </td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <a href="@Url.Action("Update", "Site", new { id = site.Id })" class="btn btn-primary">Edit</a>
                        @using (Html.BeginForm("Delete", "Site", new { id = site.Id }, FormMethod.Post))
                        {
                            <button type="submit" class="btn btn-danger">Delete</button>
                        }
                    </td>
                }
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <p>No employees found.</p>
}

<nav aria-label="...">
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.NumberPage; i++)
        {
            int page;
            @if (Context.Request.Query["page"].ToString() == "")
            {
                page = 1;
            }
            else
            {
                page = int.Parse(Context.Request.Query["page"].ToString());
            }
            <li class="page-item @(page == i ? "active" : "")">
                <a class="page-link" href="/Service/Index?page=@i">@i</a>
            </li>
        }
    </ul>
</nav>

annuaire/Views/Site/Update.cshtml
@model annuaire.Models.Site
@{
    ViewBag.Title = "Mettre à jour";
    Layout = "_Layout";
}

<h2>@Model.City : @Model.Description</h2>

@if (User.Identity!.IsAuthenticated)
{
    <form method="POST" asp-action="Update" asp-controller="Site">
        <input type="hidden" name="Id" value="@Model.Id"/>
        <label>Ville</label>
        <input asp-for="City" class="form-control" type="text" name="City" value="@Model.City"/>
        <span asp-validation-for="City"></span>
        <br/>
        <label>Description</label>
        <input asp-for="Description" class="form-control" type="text" name="Description" value="@Model.Description"/>
        <span asp-validation-for="Description"></span>
        <br/>
        <input class="btn btn-success" type="submit" value="Mettre à jour"/>
    </form>
}
else
{
    <div class="d-flex">
        <label>Ville</label>
        <input class="form-control" type="text" name="City" value="@Model.City"/>
        <br/>
        <label>Description</label>
        <input class="form-control" type="text" name="Description" value="@Model.Description"/>
        <br/>
    </div>
}